---
- hosts: docker
  become: yes
  remote_user: ubuntu
  become_user: root
  tasks:
    - name: Update all current packets
      ansible.builtin.apt:
        name: "*"
        update_cache: yes

    - name: Install pre-requirements
      ansible.builtin.apt:
        name:
          - "ca-certificates"
          - "curl"
          - "gnupg"
          - "lsb-release"
          - "apt-transport-https"
          - "software-properties-common"
          - "python3-pip"
          - "virtualenv"
          - "python3-setuptools"
        state: latest
        update_cache: yes

    - name: Enable Docker Offical key
      apt_key: url=https://download.docker.com/linux/ubuntu/gpg state=present
      become: yes
    
    - name: Enable Docker Offical Repo
      apt_repository: repo='deb https://download.docker.com/linux/ubuntu jammy stable' state=present
      become: yes

    - name: Update apt and install docker-ce
      apt:
        name: docker-ce
        state: latest
        update_cache: true

    - name: Install Docker Module for Python
      pip:
        name: docker

    - name: Log into DockerHub
      docker_login:
        username: "{{ user }}"
        password: "{{ pass }}"
    
    - name: Pull image from DockerHub
      docker_image:
        name: nginx:latest
        source: pull
